### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by volodimier** [antkorwin/xsync#1]
This library cannot be used until License is specified.

**Comment by garpinc** [comment]
I too want to know what the license is.. Please advise..

**Comment by antkorwin** [comment]
Hi, I'm sorry, I missed a notification about this issue.

I added license file in the root folder and made a note about license in the readme file. 

I have to make a new release in a pair of days...
By the way, license notice had in pom file of the previous version.

**Comment by antkorwin** [comment]
I published a new release on the maven-central, you can use it:

```
<dependency>
  <groupId>com.antkorwin</groupId>
  <artifactId>xsync</artifactId>
  <version>1.2</version>
</dependency>
```

now with Apache 2.0 license
